# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(230, 345)
        MainWindow.setMinimumSize(QtCore.QSize(230, 345))
        MainWindow.setMaximumSize(QtCore.QSize(230, 345))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(230, 325))
        self.centralwidget.setMaximumSize(QtCore.QSize(230, 325))
        self.centralwidget.setObjectName("centralwidget")
        self.one_divide_by_x = QtWidgets.QPushButton(self.centralwidget)
        self.one_divide_by_x.setGeometry(QtCore.QRect(180, 210, 31, 31))
        self.one_divide_by_x.setObjectName("one_divide_by_x")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(20, 210, 31, 31))
        self.four.setObjectName("four")
        self.mminus = QtWidgets.QPushButton(self.centralwidget)
        self.mminus.setGeometry(QtCore.QRect(180, 90, 31, 31))
        self.mminus.setObjectName("mminus")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(60, 170, 31, 31))
        self.eight.setObjectName("eight")
        self.c = QtWidgets.QPushButton(self.centralwidget)
        self.c.setGeometry(QtCore.QRect(100, 130, 31, 31))
        self.c.setObjectName("c")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(60, 250, 31, 31))
        self.two.setObjectName("two")
        self.ce = QtWidgets.QPushButton(self.centralwidget)
        self.ce.setGeometry(QtCore.QRect(60, 130, 31, 31))
        self.ce.setObjectName("ce")
        self.comma = QtWidgets.QPushButton(self.centralwidget)
        self.comma.setGeometry(QtCore.QRect(100, 290, 31, 31))
        self.comma.setObjectName("comma")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(140, 210, 31, 31))
        self.multiply.setObjectName("multiply")
        self.percent = QtWidgets.QPushButton(self.centralwidget)
        self.percent.setGeometry(QtCore.QRect(180, 170, 31, 31))
        self.percent.setObjectName("percent")
        self.equality = QtWidgets.QPushButton(self.centralwidget)
        self.equality.setGeometry(QtCore.QRect(180, 250, 31, 71))
        self.equality.setObjectName("equality")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(140, 290, 31, 31))
        self.plus.setObjectName("plus")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(100, 250, 31, 31))
        self.three.setObjectName("three")
        self.mr = QtWidgets.QPushButton(self.centralwidget)
        self.mr.setGeometry(QtCore.QRect(60, 90, 31, 31))
        self.mr.setObjectName("mr")
        self.mc = QtWidgets.QPushButton(self.centralwidget)
        self.mc.setGeometry(QtCore.QRect(20, 90, 31, 31))
        self.mc.setObjectName("mc")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(140, 250, 31, 31))
        self.minus.setObjectName("minus")
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(140, 170, 31, 31))
        self.divide.setObjectName("divide")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(20, 250, 31, 31))
        self.one.setObjectName("one")
        self.mplus = QtWidgets.QPushButton(self.centralwidget)
        self.mplus.setGeometry(QtCore.QRect(140, 90, 31, 31))
        self.mplus.setObjectName("mplus")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(20, 290, 71, 31))
        self.zero.setObjectName("zero")
        self.bdel = QtWidgets.QPushButton(self.centralwidget)
        self.bdel.setGeometry(QtCore.QRect(20, 130, 31, 31))
        self.bdel.setObjectName("bdel")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(100, 170, 31, 31))
        self.nine.setObjectName("nine")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(60, 210, 31, 31))
        self.five.setObjectName("five")
        self.switch_sign = QtWidgets.QPushButton(self.centralwidget)
        self.switch_sign.setGeometry(QtCore.QRect(140, 130, 31, 31))
        self.switch_sign.setObjectName("switch_sign")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(100, 210, 31, 31))
        self.six.setObjectName("six")
        self.radical = QtWidgets.QPushButton(self.centralwidget)
        self.radical.setGeometry(QtCore.QRect(180, 130, 31, 31))
        self.radical.setObjectName("radical")
        self.ms = QtWidgets.QPushButton(self.centralwidget)
        self.ms.setGeometry(QtCore.QRect(100, 90, 31, 31))
        self.ms.setObjectName("ms")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(20, 170, 31, 31))
        self.seven.setObjectName("seven")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.one_divide_by_x.setText(_translate("MainWindow", "1/x"))
        self.four.setText(_translate("MainWindow", "4"))
        self.mminus.setText(_translate("MainWindow", "M-"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.c.setText(_translate("MainWindow", "C"))
        self.two.setText(_translate("MainWindow", "2"))
        self.ce.setText(_translate("MainWindow", "CE"))
        self.comma.setText(_translate("MainWindow", "."))
        self.multiply.setText(_translate("MainWindow", "*"))
        self.percent.setText(_translate("MainWindow", "%"))
        self.equality.setText(_translate("MainWindow", "="))
        self.plus.setText(_translate("MainWindow", "+"))
        self.three.setText(_translate("MainWindow", "3"))
        self.mr.setText(_translate("MainWindow", "MR"))
        self.mc.setText(_translate("MainWindow", "MC"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.one.setText(_translate("MainWindow", "1"))
        self.mplus.setText(_translate("MainWindow", "M+"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.bdel.setText(_translate("MainWindow", "←"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.five.setText(_translate("MainWindow", "5"))
        self.switch_sign.setText(_translate("MainWindow", "±"))
        self.six.setText(_translate("MainWindow", "6"))
        self.radical.setText(_translate("MainWindow", "√"))
        self.ms.setText(_translate("MainWindow", "MS"))
        self.seven.setText(_translate("MainWindow", "7"))

